import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/sidebar'
import { ThemeProvider } from '@/components/next-theme'
import { ThemeToggle } from '@/components/ui/theme-toggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="h-screen overflow-hidden">
            <div className="border-t">
              <div className="bg-background">
                <header className="flex py-2 lg:px-8 px-4 justify-between items-center border-b w-full">
                  <h2 className="md:text-2xl text-lg font-semibold tracking-tight">
                    PicLike
                  </h2>
                  <ThemeToggle />
                </header>
                <div className="flex h-[calc(100vh-53px)]">
                  <Sidebar className="h-screen border-r xl:block hidden" />
                  <div className="w-full flex-1">{children}</div>
                </div>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
